### ISSUE TITLE
Unable to start container

### ISSUE THREAD

**Issue by mavencode01** [mondediefr/flarum#2]
Unable to start container, not sure why `su-exec` and `config.sql` is not being resolved - No such file or directory.

Any idea ?

	flarum     | [INFO] First launch, installing flarum...
	flarum     | sed: config.sql: No such file or directory
	flarum     | su-exec: #: No such file or directory
	flarum     | /usr/local/bin/run.sh: line 112: can't open config.sql: no such file
	flarum     | [INFO] Installation done, launch flarum...
	flarum     | chown: #: No such file or directory
	flarum     | chown: Optional:991: No such file or directory
	flarum     | chown: #: No such file or directory
	flarum     | chown: Optional: No such file or directory
	flarum     | su-exec: #: No such file or directory

**Comment by hardware** [comment]
Hi,

Can you please link your `docker-composer.yml` file and give the result of `docker version` and `docker info` ?

**Comment by mavencode01** [comment]
Sure, 
docker-vesion: `Docker version 1.12.2-rc1, build 45bed2c, experimental`

Here is my docker-compose.yml

  
      flarum:
         image: pkadetiloye/flarum
         container_name: flarum
         env_file: ./.config/flarum/.env
         links:
         - mariadb:mariadb
         volumes:
         - ./flarum:/flarum/app/assets

    mariadb:
      image: mariadb:10.1
      container_name: mariadb
      volumes:
        - ./mysql/db:/var/lib/mysql
      environment:
        - MYSQL_ROOT_PASSWORD=xxxxxxxx
        - MYSQL_DATABASE=flarum
        - MYSQL_USER=flarum
        - MYSQL_PASSWORD=yyyyyyyy

## Docker Info

	Containers: 12
	 Running: 1
	 Paused: 0
	 Stopped: 11
	Images: 43
	Server Version: 1.12.2-rc1
	Storage Driver: aufs
	 Root Dir: /var/lib/docker/aufs
	 Backing Filesystem: extfs
	 Dirs: 131
	 Dirperm1 Supported: true
	Logging Driver: json-file
	Cgroup Driver: cgroupfs
	Plugins:
	 Volume: local
	 Network: bridge null host overlay
	Swarm: inactive
	Runtimes: runc
	Default Runtime: runc
	Security Options: seccomp
	Kernel Version: 4.4.22-moby
	Operating System: Alpine Linux v3.4
	OSType: linux
	Architecture: x86_64
	CPUs: 4
	Total Memory: 1.952 GiB
	Name: moby
	ID: GNCF:LJJR:G4ZA:YSHR:X4T3:TT46:7X35:UOL3:LDMY:BQB7:I5JY:VXK7
	Docker Root Dir: /var/lib/docker
	Debug Mode (client): false
	Debug Mode (server): true
	 File Descriptors: 23
	 Goroutines: 54
	 System Time: 2016-10-03T21:18:01.585922646Z
	 EventsListeners: 1
	No Proxy: *.local, 169.254/16
	Registry: https://index.docker.io/v1/
	Experimental: true
	Insecure Registries:
	 127.0.0.0/8

**Comment by hardware** [comment]
I have not tested yet with the last docker release candidate `1.12.2-rc1`.
 
Can you please try with `mondedie/flarum` instead of `pkadetiloye/flarum` and use an absolute path for your volumes maybe.

**Comment by mavencode01** [comment]
I just tested  with `mondedie/flarum` same issue.

**Comment by hardware** [comment]
I think this probem is related to the host OS or something with the fs driver, try with another version of AUFS. You could also try with btrfs or overlay filesystem.

In my side, It works well wit the last Debian 8.6 on host with docker 1.12.1 (aufs)

**Comment by mavencode01** [comment]
Actually, I made the mistake of copying verbatim the ENV file as-is and just editing it.
Those comments were actually read into the variables for example 
`UID=991                        #Optional`
causing the `chown` and `su-exec` commands to freak out. 

```
UID=991                              # Optional
GID=991                              # Optional

FORUM_URL=https://forum.domain.tld/  # Required

DB_HOST=mariadb                      # Optional
DB_NAME=flarum                       # Optional
DB_USER=flarum                       # Optional
DB_PASS=yyyyyyyy                     # Required

MAIL_FROM=noreply@domain.tld         # Optional
MAIL_HOST=mail.domain.tld            # Optional
MAIL_PORT=465                        # Optional
MAIL_ENCR=ssl                        # Optional
MAIL_USER=admin@domain.tld           # Optional
MAIL_PASS=xxxxxxxx                   # Optional
```


Closing this issue, thank you.
